apiVersion: apps/v1
kind: Deployement
metadata:
  name: api
  labels:
    component: api
    app: todo
spec:
  replicas: 2
  template:
    metadata:
      labels:
        component: api
        app: todo
  containers:
  - name: api
    image: icclabcna/ccp2-k8s-todo-api
    ports:
    - containerPort: 8081
    env:
    - name: REDIS_ENDPOINT
      value: redis-svc
    - name: REDIS_PWD
      value: ccp2
