apiVersion: v1
kind: Service
metadata:
  labels:
    component: frontend
  name: frontend-svc

spec:
  selector:
    app: todo
    component: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: frontend
  clusterIP: 10.96.171.239
  type: LoadBalancer

status:
  loadBalancer:
    ingress:
    - ip: 192.0.2.127
  

